/**
  This file was autogenerated by ResampleCodeGen.m
  Author: Chris Fogelklou
  Command: ResampleCodeGen(2, 3480, 8000, 1, 0, DownsampleX1Coeffs)
*/
// Include files
#include "AudResampler.h"


// The FIR coefficients for this filter 

static const ar_coef firCoeffs[] = {
	(ar_coef)1.0,
	0
};

// The resampler configuration struct
const AudResampleConfig DownsampleX1CoeffsCfg = {
  (sizeof(firCoeffs) / sizeof(ar_coef)),
  1,
  -1,
  firCoeffs
};
